# 1. Tensor

- 배열이나 행렬과 매우 유사한 특수한 자료구조

In [1]:
import torch
import numpy as np

## 1-1. 텐서 초기화하기

In [2]:
data = [[1,2],[3,4]]

### 1) 데이터로부터 직접 생성하기

In [3]:
X_data = torch.tensor(data)

In [4]:
X_data

tensor([[1, 2],
        [3, 4]])

### 2) NumPy 배열로부터 생성하기

In [6]:
np_array = np.array(data)
X_np = torch.from_numpy(np_array)

In [7]:
X_np

tensor([[1, 2],
        [3, 4]])

### 3) 다른 텐서로부터 생성하기

- ones_like : 1로 채워진 텐서
- zeros_like : 0으로 채워진 텐서
- rand_like : 랜덤으로

In [9]:
X_ones = torch.ones_like(X_data)

X_rand = torch.rand_like(X_data,dtype = torch.float)

print(f"Ones Tensor : \n {X_ones} \n")
print(f"Random Tensor : \n {X_rand} \n")

Ones Tensor : 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor : 
 tensor([[0.5365, 0.1966],
        [0.2560, 0.8337]]) 



### 4) 무작위 또는 상수 값을 사용하기

In [10]:
shape = (2,3,)

In [12]:
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Rand Tensor : \n {rand_tensor} \n")
print(f"Ones Tensor : \n {ones_tensor} \n")
print(f"Zeros Tensor : \n {zeros_tensor} \n")

Rand Tensor : 
 tensor([[0.9388, 0.2545, 0.9413],
        [0.2147, 0.9543, 0.6911]]) 

Ones Tensor : 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor : 
 tensor([[0., 0., 0.],
        [0., 0., 0.]]) 



## 1-2. 텐서의 속성(Attribute)

- 텐서의 속성은 텐서의 모양, 자료형 및 어느 장치에 저장되는지 나타내준다.

In [16]:
tensor = torch.rand(3,4)

In [18]:
print(f"Shape of Tensor : {tensor.shape}")
print(f"Datatype of Tensor : {tensor.dtype}")
print(f"Device Tensor is stored on : {tensor.device}")

Shape of Tensor : torch.Size([3, 4])
Datatype of Tensor : torch.float32
Device Tensor is stored on : cpu


## 1-3. 텐서 연산 (Operation)

- 전치, 인덱싱, 슬라이싱, 수학 계산, 선형 대수, 임의 샘플링 등 100가지 이상의 텐서 연산을 수행할 수 있다.

In [19]:
if torch.cuda.is_available() :
    tensor = tensor.to('cuda')
    print(f"Device Tensor is stored on : {tensor.device}")

In [20]:
tensor = torch.ones(4,4)

In [24]:
tensor[:,1] = 0 # 처음은 행 두번째는 열
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


### 3-1. 텐서 합치기

In [28]:
t0 = torch.cat([tensor,tensor,tensor],dim = 0)
t1 = torch.cat([tensor,tensor,tensor],dim = 1)

print(f"행으로 붙인 결과 \n {t0} \n")
print(f"열로 붙인 결과 \n {t1} \n")

행으로 붙인 결과 
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

열로 붙인 결과 
 tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]]) 



- dim이 0이면 행으로 붙이기, 1이면 열로 붙이기

### 3-2 텐서 곱하기

In [29]:
tensor.mul(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [30]:
print(f"요소별 곱을 계산 \n {tensor.mul(tensor)}\n")
print(f"위와 같은 결과 \n {tensor * tensor}")

요소별 곱을 계산 
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

위와 같은 결과 
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [31]:
print(f"두 텐서 간의 행렬 곱 \n{tensor.matmul(tensor.T)} \n")
print(f"위와 동일한 결과 \n {tensor @ tensor}")

두 텐서 간의 행렬 곱 
tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]]) 

위와 동일한 결과 
 tensor([[3., 0., 3., 3.],
        [3., 0., 3., 3.],
        [3., 0., 3., 3.],
        [3., 0., 3., 3.]])


### 3-3. 바꿔치기 연산

- 접미사를 갖는 연산들은 바꿔치기(in-place) 연산한다

In [34]:
print(tensor,"\n")
tensor.add_(5)
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


- 계산 파라미터 뒤에 _ 붙은거는 따로 정의안해줘도 적용

## 1-4 Numpy 변환(Bridge)

### 4-1. 텐서를 numpy 배열로 변환하기

In [37]:
t = torch.ones(5)
print(f"t : {t}")
n = t.numpy()
print(f"n : {n}")

t : tensor([1., 1., 1., 1., 1.])
n : [1. 1. 1. 1. 1.]


In [38]:
t.add_(1)
print(t,"\n")
print(n,"\n")

tensor([2., 2., 2., 2., 2.]) 

[2. 2. 2. 2. 2.] 



### 4-2. NumPy 배열 Tensor로 변환하기

In [39]:
n = np.ones(5)
t = torch.from_numpy(n)

In [40]:
print(n,'\n')
print(t)

[1. 1. 1. 1. 1.] 

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [41]:
np.add(n,1,out = n)
print(f"t : {t}\n")
print(f"n : {n}\n")

t : tensor([2., 2., 2., 2., 2.], dtype=torch.float64)

n : [2. 2. 2. 2. 2.]

