### 단순 선형 회귀 구현

In [4]:
import torch
from torch import nn
from torch.nn import functional as F

torch.manual_seed(1)

In [5]:
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])

In [6]:
model = nn.Linear(1,1)

In [9]:
print(list(model.parameters()))

[Parameter containing:
tensor([[0.5153]], requires_grad=True), Parameter containing:
tensor([-0.4414], requires_grad=True)]


- 첫 번째 텐서는 W, 두 번째 tensor는 b

In [10]:
optimizer = torch.optim.SGD(model.parameters(),lr = 0.01)

In [12]:
epochs = 2000
for epoch in range(1,epochs+1) :
    
    prediction = model(x_train)
    
    cost = F.mse_loss(prediction,y_train)
    
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    if epoch % 100 == 0 :
        print(f"Epoch {epoch}/{epochs} Cost : {cost.item()}")

Epoch 100/2000 Cost : 0.002804068149998784
Epoch 200/2000 Cost : 0.0017327357782050967
Epoch 300/2000 Cost : 0.0010707209585234523
Epoch 400/2000 Cost : 0.0006616427563130856
Epoch 500/2000 Cost : 0.0004088581772521138
Epoch 600/2000 Cost : 0.0002526498574297875
Epoch 700/2000 Cost : 0.00015612124116159976
Epoch 800/2000 Cost : 9.647066326579079e-05
Epoch 900/2000 Cost : 5.9613765188260004e-05
Epoch 1000/2000 Cost : 3.683911927510053e-05
Epoch 1100/2000 Cost : 2.2764041204936802e-05
Epoch 1200/2000 Cost : 1.4065827599551994e-05
Epoch 1300/2000 Cost : 8.692571100255009e-06
Epoch 1400/2000 Cost : 5.371515726437792e-06
Epoch 1500/2000 Cost : 3.319054485473316e-06
Epoch 1600/2000 Cost : 2.0513498384389095e-06
Epoch 1700/2000 Cost : 1.2677684253503685e-06
Epoch 1800/2000 Cost : 7.839325348868442e-07
Epoch 1900/2000 Cost : 4.845924195251428e-07
Epoch 2000/2000 Cost : 2.9956314051560184e-07


In [13]:
new_var = torch.FloatTensor([[4.0]])

pred_y = model(new_var)

print(f"학습 후 입력이 4일 때 예측 값 : {pred_y}")

학습 후 입력이 4일 때 예측 값 : tensor([[7.9989]], grad_fn=<AddmmBackward0>)


In [14]:
print(list(model.parameters()))

[Parameter containing:
tensor([[1.9994]], requires_grad=True), Parameter containing:
tensor([0.0014], requires_grad=True)]


### 다중 선형 회귀 구현

In [15]:
X_train = torch.FloatTensor([[73, 80, 75],
                             [93, 88, 93],
                             [89, 91, 90],
                             [96, 98, 100],
                             [73, 66, 70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

In [22]:
torch.manual_seed(1)

In [23]:
model = nn.Linear(3,1)

In [24]:
print(list(model.parameters()))

[Parameter containing:
tensor([[ 0.2975, -0.2548, -0.1119]], requires_grad=True), Parameter containing:
tensor([0.2710], requires_grad=True)]


- 가중치 : w1(0.2975), w2(-0.2548), w3(-0.1119)
- 편향(b) : 0.2710

In [25]:
optimizer = torch.optim.SGD(model.parameters(),lr = 1e-5)

In [26]:
epochs = 2000
for epoch in range(1,epochs+1) :
    prediction = model(X_train)
    
    cost = F.mse_loss(prediction,y_train)
    
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    if epoch % 100 == 0:
    # 100번마다 로그 출력
      print('Epoch {:4d}/{} Cost: {:.6f}'.format(
          epoch, epochs, cost.item()
      ))

Epoch  100/2000 Cost: 0.226011
Epoch  200/2000 Cost: 0.223930
Epoch  300/2000 Cost: 0.221953
Epoch  400/2000 Cost: 0.220074
Epoch  500/2000 Cost: 0.218288
Epoch  600/2000 Cost: 0.216593
Epoch  700/2000 Cost: 0.214968
Epoch  800/2000 Cost: 0.213431
Epoch  900/2000 Cost: 0.211972
Epoch 1000/2000 Cost: 0.210572
Epoch 1100/2000 Cost: 0.209247
Epoch 1200/2000 Cost: 0.207987
Epoch 1300/2000 Cost: 0.206780
Epoch 1400/2000 Cost: 0.205629
Epoch 1500/2000 Cost: 0.204536
Epoch 1600/2000 Cost: 0.203490
Epoch 1700/2000 Cost: 0.202495
Epoch 1800/2000 Cost: 0.201550
Epoch 1900/2000 Cost: 0.200642
Epoch 2000/2000 Cost: 0.199783


In [27]:
new_var = torch.FloatTensor([[73,80,75]])

pred_y = model(new_var)

print(f"학습 후 new_var의 예측값 : {pred_y}")

학습 후 new_var의 예측값 : tensor([[151.2305]], grad_fn=<AddmmBackward0>)


In [28]:
print(list(model.parameters()))

[Parameter containing:
tensor([[0.9778, 0.4539, 0.5768]], requires_grad=True), Parameter containing:
tensor([0.2802], requires_grad=True)]
