## 1. 파이토치로 로지스틱 회귀 구현하기

In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [2]:
torch.manual_seed(1)

In [4]:
X_data = [[1, 2], [2, 3], [3, 1], [4, 3], [5, 3], [6, 2]]
y_data = [[0], [0], [0], [1], [1], [1]]
X_train = torch.FloatTensor(X_data)
y_train = torch.FloatTensor(y_data)

In [5]:
model = nn.Sequential(
            nn.Linear(2,1), ## input_dim = 2, output_dim = 1
            nn.Sigmoid())

- Sequential : 층을 차례로 쌓을 수 있도록 한다.

In [6]:
model(X_train )

tensor([[0.4020],
        [0.4147],
        [0.6556],
        [0.5948],
        [0.6788],
        [0.8061]], grad_fn=<SigmoidBackward0>)

In [8]:
optimizer = optim.SGD(model.parameters(),lr = 1)

epochs = 1000
for epoch in range(epochs+1) :
    
    hypo = model(X_train)
    
    cost = F.binary_cross_entropy(hypo,y_train)
    
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    if epoch % 10 == 0:
        prediction = hypo >= torch.FloatTensor([0.5]) # 예측값이 0.5를 넘으면 True로 간주
        correct_prediction = prediction.float() == y_train # 실제값과 일치하는 경우만 True로 간주
        accuracy = correct_prediction.sum().item() / len(correct_prediction) # 정확도를 계산
        print('Epoch {:4d}/{} Cost: {:.6f} Accuracy {:2.2f}%'.format( # 각 에포크마다 정확도를 출력
            epoch, epochs, cost.item(), accuracy * 100,
        ))

Epoch    0/1000 Cost: 0.527002 Accuracy 83.33%
Epoch   10/1000 Cost: 0.994593 Accuracy 66.67%
Epoch   20/1000 Cost: 0.570399 Accuracy 83.33%
Epoch   30/1000 Cost: 0.473909 Accuracy 83.33%
Epoch   40/1000 Cost: 0.388606 Accuracy 83.33%
Epoch   50/1000 Cost: 0.307901 Accuracy 83.33%
Epoch   60/1000 Cost: 0.235923 Accuracy 83.33%
Epoch   70/1000 Cost: 0.182916 Accuracy 100.00%
Epoch   80/1000 Cost: 0.155795 Accuracy 100.00%
Epoch   90/1000 Cost: 0.143031 Accuracy 100.00%
Epoch  100/1000 Cost: 0.133369 Accuracy 100.00%
Epoch  110/1000 Cost: 0.124978 Accuracy 100.00%
Epoch  120/1000 Cost: 0.117600 Accuracy 100.00%
Epoch  130/1000 Cost: 0.111060 Accuracy 100.00%
Epoch  140/1000 Cost: 0.105223 Accuracy 100.00%
Epoch  150/1000 Cost: 0.099983 Accuracy 100.00%
Epoch  160/1000 Cost: 0.095251 Accuracy 100.00%
Epoch  170/1000 Cost: 0.090958 Accuracy 100.00%
Epoch  180/1000 Cost: 0.087044 Accuracy 100.00%
Epoch  190/1000 Cost: 0.083461 Accuracy 100.00%
Epoch  200/1000 Cost: 0.080169 Accuracy 100.00%

In [11]:
model(X_train)

tensor([[2.7553e-04],
        [3.1567e-02],
        [3.8923e-02],
        [9.5627e-01],
        [9.9824e-01],
        [9.9969e-01]], grad_fn=<SigmoidBackward0>)

In [12]:
print(list(model.parameters()))

[Parameter containing:
tensor([[3.2543, 1.5186]], requires_grad=True), Parameter containing:
tensor([-14.4881], requires_grad=True)]


## 2. 클래스로 구현하기

In [13]:
class BinaryClassifier(nn.Module) :
    def __init__(self) :
        super().__init__()
        self.linear = nn.Linear(2,1)
        self.sigmoid = nn.Sigmoid()
        
    def forward(self,x) :
        return self.sigmoid(self.linear(x))

In [16]:
model = BinaryClassifier()

In [17]:
optimizer = optim.SGD(model.parameters(),lr = 1)

In [19]:
X_train = torch.FloatTensor(X_data)
y_train = torch.FloatTensor(y_data)

In [22]:
for epoch in range(1001): 
    prediction = model(X_train) 
    loss = F.binary_cross_entropy(prediction, y_train) 
    optimizer.zero_grad() 
    loss.backward() 
    optimizer.step()
    print(loss.item())


0.6149943470954895
0.8097653388977051
1.2156200408935547
2.2787606716156006
0.5576614737510681
0.62872314453125
0.9388265609741211
0.7147286534309387
1.116650938987732
0.5795651078224182
0.7475497126579285
0.5937384963035583
0.7956371307373047
0.558070957660675
0.7197175025939941
0.5357170104980469
0.6844151020050049
0.5155693888664246
0.6562498807907104
0.4974443018436432
0.633215606212616
0.48057207465171814
0.6126231551170349
0.4645887315273285
0.5932491421699524
0.4493136405944824
0.5745265483856201
0.43465033173561096
0.5561920404434204
0.4205404222011566
0.5381225943565369
0.40694180130958557
0.5202576518058777
0.3938194513320923
0.5025671124458313
0.38114118576049805
0.485033243894577
0.36887654662132263
0.4676482379436493
0.35699495673179626
0.4504058361053467
0.34546664357185364
0.4333040714263916
0.3342630863189697
0.41634491086006165
0.3233560621738434
0.39953184127807617
0.3127188980579376
0.38287338614463806
0.3023265302181244
0.36638179421424866
0.2921566665172577
0.35007

0.02593541145324707
0.025903800502419472
0.02587229199707508
0.02584085427224636
0.02580944634974003
0.025778165087103844
0.025746935978531837
0.02571580372750759
0.025684768334031105
0.025653785094618797
0.025622857734560966
0.025592023506760597
0.025561252608895302
0.02553059160709381
0.025499999523162842
0.02546943537890911
0.02543899416923523
0.02540859766304493
0.025378309190273285
0.025348030030727386
0.025317847728729248
0.025287756696343422
0.025257734581828117
0.02522776462137699
0.025197908282279968
0.02516808919608593
0.02513834275305271
0.02510868012905121
0.025079092010855675
0.025049567222595215
0.025020090863108635
0.024990713223814964
0.024961384013295174
0.024932116270065308
0.02490297146141529
0.024873822927474976
0.024844810366630554
0.024815818294882774
0.0247869323939085
0.024758070707321167
0.02472931146621704
0.02470060996711254
0.024671966210007668
0.024643411859869957
0.024614891037344933
0.024586452171206474
0.024558106437325478
0.02452980726957321
0.024501526