## 1. 미니 배치와 배치 크기

In [1]:
import torch

In [2]:
X_train = torch.FloatTensor([[73, 80, 75],
                             [93, 88, 93],
                             [89, 91, 90],
                             [96, 98, 100],
                             [73, 66, 70]])

y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

In [3]:
X_train.shape

torch.Size([5, 3])

- 데이터의 샘플 수는 5개여서 전체 데이터에 대해서 경사 하강법을 수행하여 학습이 가능
- 그러나 현업에서는 방대한 양의 데이터를 다루기에 전체 데이터에 대해 경사하강법을 수행하면 매우 느리고 많은 계산량이 필요 -> 더 작은 단위로 나누어 해당 단위로 학습 -> 이 것이 미니 배치(Mini Batch)

- 미니 배치 학습을 하게 된다면 미니 배치만큼 가져가서 미니 배치에 대한 비용을 계산한 후 경사 하강법 수행, 순서대로 경사 하강법 수행하고 반복.
- 이렇게 전체 데이터에 대한 학습이 1회 끝나면 1 에포크(epoch) 끝
- 미니 배치 크기 : batch size
- 배치 크기는 보통 2의 제곱수를 활용 -> CPU&GPU의 메모리가 2의 배수이기에 2의 제곱수일 경우 데이터 송수신 효율 높일 수 있다.

## 2. 이터레이션(Iteration)

#### 전체 데이터가 2,000개일 경우

- 배치 크기를 200으로 하면 이터레이션 수는 10개
- 이는 한 번의 에포크 당 매개변수(W,b) 업데이트를 10번 이루어진다

## 3. 데이터 로드(Data Load)

In [4]:
import torch
from torch import nn
import torch.nn.functional as F

In [5]:
from torch.utils.data import TensorDataset # 텐서데이터셋
from torch.utils.data import DataLoader

In [6]:
X_train  =  torch.FloatTensor([[73,  80,  75], 
                               [93,  88,  93], 
                               [89,  91,  90], 
                               [96,  98,  100],   
                               [73,  66,  70]])  
y_train  =  torch.FloatTensor([[152],  [185],  [180],  [196],  [142]])

In [8]:
dataset = TensorDataset(X_train,y_train)

In [10]:
dataset.tensors

(tensor([[ 73.,  80.,  75.],
         [ 93.,  88.,  93.],
         [ 89.,  91.,  90.],
         [ 96.,  98., 100.],
         [ 73.,  66.,  70.]]),
 tensor([[152.],
         [185.],
         [180.],
         [196.],
         [142.]]))

In [11]:
dataloader = DataLoader(dataset,batch_size=2,shuffle=True)

- 데이터로더는 기본적으로 2개의 인자를 받는다.
- 하나는 데이터셋, 하나는 미니 배치 크기(크기는 2의 배수(ex. 32,64,128....))
- shuffle : epoch마다 데이터셋 섞는다.

In [12]:
model = nn.Linear(3,1)
optimizer = torch.optim.SGD(model.parameters(),lr = 1e-5)

In [18]:
epochs = 20
for epoch in range(1,epochs+1) :
    for batch_idx, samples in enumerate(dataloader) :
        X_train,y_train = samples
        
        prediction = model(X_train)
        
        cost = F.mse_loss(prediction,y_train)
        
        optimizer.zero_grad()
        cost.backward()
        optimizer.step()
        
        
        print(f"Epoch {epoch}/{epochs} Batch {batch_idx+1}/{len(dataloader)} Cost : {round(cost.item(),3)}")

Epoch 1/20 Batch 1/3 Cost : 18223.535
Epoch 1/20 Batch 2/3 Cost : 12890.672
Epoch 1/20 Batch 3/3 Cost : 3580.65
Epoch 2/20 Batch 1/3 Cost : 543.271
Epoch 2/20 Batch 2/3 Cost : 241.828
Epoch 2/20 Batch 3/3 Cost : 26.857
Epoch 3/20 Batch 1/3 Cost : 31.017
Epoch 3/20 Batch 2/3 Cost : 9.153
Epoch 3/20 Batch 3/3 Cost : 0.149
Epoch 4/20 Batch 1/3 Cost : 7.243
Epoch 4/20 Batch 2/3 Cost : 1.09
Epoch 4/20 Batch 3/3 Cost : 5.725
Epoch 5/20 Batch 1/3 Cost : 5.992
Epoch 5/20 Batch 2/3 Cost : 1.258
Epoch 5/20 Batch 3/3 Cost : 1.009
Epoch 6/20 Batch 1/3 Cost : 5.977
Epoch 6/20 Batch 2/3 Cost : 1.43
Epoch 6/20 Batch 3/3 Cost : 0.837
Epoch 7/20 Batch 1/3 Cost : 1.673
Epoch 7/20 Batch 2/3 Cost : 2.292
Epoch 7/20 Batch 3/3 Cost : 11.351
Epoch 8/20 Batch 1/3 Cost : 1.268
Epoch 8/20 Batch 2/3 Cost : 6.096
Epoch 8/20 Batch 3/3 Cost : 1.039
Epoch 9/20 Batch 1/3 Cost : 4.515
Epoch 9/20 Batch 2/3 Cost : 3.215
Epoch 9/20 Batch 3/3 Cost : 0.561
Epoch 10/20 Batch 1/3 Cost : 6.05
Epoch 10/20 Batch 2/3 Cost : 1.49

In [19]:
new_var = torch.FloatTensor([[73,80,75]])

In [22]:
pred_y = model(new_var)

In [23]:
pred_y

tensor([[153.0993]], grad_fn=<AddmmBackward0>)